# Generated by Django 6.0.1 on 2026-01-20 19:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('skill', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opensource', models.BooleanField(default=False)),
                ('paidprojects', models.BooleanField(default=False)),
                ('startup', models.BooleanField(default=False)),
                ('mentorship', models.BooleanField(default=False)),
                ('weeklyhour', models.PositiveIntegerField(default=0)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colab', to='Auth_System.details')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('headline', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
                ('visibility', models.CharField(max_length=20)),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='Auth_System.details')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformUsernameDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfusername', models.CharField(max_length=100)),
                ('gitusername', models.CharField(max_length=100)),
                ('stackusername', models.CharField(max_length=100)),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platformusername', to='Auth_System.details')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('schoolname', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('startdate', models.CharField(max_length=10)),
                ('enddate', models.CharField(blank=True, max_length=100, null=True)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='Auth_System.details')),
            ],
        ),
        migrations.CreateModel(
            name='UserProjectDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('githublink', models.URLField()),
                ('livelink', models.URLField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Auth_System.details')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_skills', to='Auth_System.skilllist')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectskills', to='Auth_System.userprojectdetails')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='Auth_System.details')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Auth_System.skilllist')),
            ],
            options={
                'unique_together': {('details', 'skill')},
            },
        ),
    ]
