# Generated by Django 5.2.6 on 2026-01-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth_System", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="current",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="studentdetails",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentdetails",
            name="enddate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="studentdetails",
            name="field",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
