# Generated by Django 5.2.6 on 2026-01-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Auth_System", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentdetails",
            old_name="descritpion",
            new_name="description",
        ),
    ]
