# Generated by Django 6.0.1 on 2026-01-14 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_System', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboration',
            name='mentorship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaboration',
            name='opensource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaboration',
            name='paidprojects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaboration',
            name='startup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaboration',
            name='weeklyhour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectskills',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectskills', to='Auth_System.userprojectdetails'),
        ),
        migrations.AlterField(
            model_name='projectskills',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_skills', to='Auth_System.skilllist'),
        ),
    ]
