# Generated by Django 5.1.6 on 2026-01-01 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colab', to='Auth_System.details')),
            ],
        ),
    ]
