# Generated by Django 5.2.6 on 2026-01-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth_System", "0002_rename_descritpion_studentdetails_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdetails",
            name="description",
            field=models.TextField(),
        ),
    ]
