# Generated by Django 5.2.6 on 2025-12-28 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth_System", "0003_alter_details_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("contactemail", models.CharField(max_length=100)),
                ("portfolioLink", models.URLField(blank=True, null=True)),
                ("country", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("currentStatus", models.CharField(max_length=100)),
                ("preferredRole", models.CharField(max_length=100)),
                (
                    "details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal",
                        to="Auth_System.details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlatfromUsernameDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codeforces", models.CharField(max_length=100)),
                ("github", models.CharField(max_length=100)),
                ("stackoverflow", models.CharField(max_length=100)),
                (
                    "detials",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="username",
                        to="Auth_System.details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=100)),
                ("field", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=100)),
                (
                    "details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student",
                        to="Auth_System.details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yearexperience", models.PositiveIntegerField()),
                ("workingprofile", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                (
                    "details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional",
                        to="Auth_System.details",
                    ),
                ),
            ],
        ),
    ]
