# Generated by Django 5.1.6 on 2026-01-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_System', '0003_alter_studentdetails_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdetails',
            options={'ordering': ['-number']},
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_System.details'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='schoolname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
