# Generated by Django 5.2.6 on 2026-01-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Auth_System", "0002_alter_studentdetails_current_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problemsolving", models.PositiveIntegerField()),
                ("engineering", models.PositiveIntegerField()),
                ("knowledge", models.PositiveIntegerField()),
                ("consistency", models.PositiveIntegerField()),
                ("impact", models.PositiveIntegerField()),
                (
                    "details",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level",
                        to="Auth_System.details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.PositiveIntegerField()),
                ("month", models.CharField(max_length=30)),
                ("level", models.PositiveIntegerField()),
                (
                    "details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="Auth_System.details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSkillBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skillname", models.CharField(max_length=40)),
                ("skilllevel", models.PositiveIntegerField()),
                (
                    "details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skillbalance",
                        to="Auth_System.details",
                    ),
                ),
            ],
        ),
    ]
