# Generated by Django 6.0.1 on 2026-01-20 19:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth_System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('project_title', models.CharField(max_length=50)),
                ('project_summary', models.CharField(max_length=200)),
                ('project_visibility', models.CharField(max_length=20)),
                ('project_category', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_System.details')),
            ],
        ),
        migrations.CreateModel(
            name='Deliverables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_id', models.PositiveIntegerField()),
                ('deliverable_name', models.CharField(max_length=100)),
                ('completed', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teammate_core.postproject')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_commitment', models.CharField(choices=[('part-time', 'Part-time (10-20 hrs/week)'), ('full-time', 'Full-time (30+ hrs/week)')], max_length=30)),
                ('collaboration_style', models.CharField(choices=[('async', 'Async First'), ('sync', 'Synchronous')], max_length=20)),
                ('communication_norms', models.TextField(blank=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Teammate_core.postproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField()),
                ('time_zone_preferred', models.CharField()),
                ('end_date', models.CharField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teammate_core.postproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNarrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField()),
                ('problem_solution', models.TextField()),
                ('repo_link', models.URLField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Teammate_core.postproject')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_member_number', models.PositiveIntegerField()),
                ('min_rating', models.PositiveIntegerField(default=0)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Teammate_core.postproject')),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teammate_core.postproject')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_System.skilllist')),
            ],
        ),
    ]
