# Generated by Django 6.0.1 on 2026-01-14 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth_System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('projecttitle', models.CharField(max_length=20)),
                ('projectsummary', models.CharField(max_length=100)),
                ('projectdescription', models.CharField(max_length=500)),
                ('projectvisibility', models.CharField(max_length=20)),
                ('projectcategory', models.CharField(max_length=30)),
                ('desiredteammember', models.PositiveIntegerField()),
                ('ratingrequired', models.PositiveIntegerField()),
                ('currentteammember', models.PositiveIntegerField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PostProject', to='Auth_System.details')),
            ],
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='Teammate_core.postproject')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membernumber', models.PositiveIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth_System.details')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teammate_core.postproject')),
            ],
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techstack', to='Teammate_core.postproject')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='Auth_System.skilllist')),
            ],
        ),
    ]
