# Generated by Django 5.1.6 on 2026-01-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teammate_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectduration',
            name='end_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='projectduration',
            name='start_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='projectduration',
            name='time_zone_preferred',
            field=models.CharField(max_length=30),
        ),
    ]
